# Used for https certificates on ingress
{{- if .Values.issuer }}
{{- with .Values.issuer }}
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: {{ .name }}
spec:
  acme:
    server: {{ .server }}
    email: {{ .email }}
    privateKeySecretRef:
      name: {{ .secretRef }}

    solvers:
    - selector:
        dnsZones:
        - 'plutomi.com'
      dns01:
        cloudflare:
          email: {{ .email }}
          apiTokenSecretRef:
            name: cloudflare-token
            key: CLOUDFLARE_TOKEN
{{- end }}
{{- end }}


